force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <description>Relationship between programs and employees that they are being assigned.</description>
    <label>Program Assignment</label>
    <nameField>
        <displayFormat>PAS-{0000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Completed_Mins__c.field-meta.xml
<CustomField>
    <fullName>Completed_Mins__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total number of minutes earned for completing a training task. When a training task is marked complete, that object&apos;s &apos;Duration Mins.&apos; field will be added to this field.</description>
    <inlineHelpText>Total number of minutes earned from completing training tasks associated with this program.</inlineHelpText>
    <label>Completed Mins.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Duration_Mins__c.field-meta.xml
<CustomField>
    <fullName>Duration_Mins__c</fullName>
    <formula>Program__r.Duration_Mins__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration Mins.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Number_of_Completed_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Completed_Tasks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Completed Tasks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Ratio between minutes earned vs. total minutes determining how far ahead or behind a user is within their assigned program. Calculated by Completed Minutes / Total Minutes by a +-25% criteria</description>
    <formula>IF(AND(Duration_Mins__c != 0, Completed_Mins__c = Duration_Mins__c), &apos;Complete&apos;,
IF(OR(Expected_Mins_Due__c = 0,AND(Expected_Mins_Due__c = 0, Completed_Mins__c = Expected_Mins_Due__c)), &apos;On Track&apos;,
IF(Completed_Mins__c / Expected_Mins_Due__c &lt;= 0.75, &apos;Far Behind&apos;,
IF(Completed_Mins__c / Expected_Mins_Due__c &lt; 1, &apos;Behind&apos;,
IF(Completed_Mins__c / Expected_Mins_Due__c &gt; 1.25, &apos;Far Ahead&apos;,
IF(Completed_Mins__c / Expected_Mins_Due__c &gt; 1, &apos;Far Ahead&apos;, &apos;N/A&apos;))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculated by Completed Mins. / Expected Mins. by a +-25% criteria (if Expected Mins. != 0)</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/Training_Task_Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction Object. Individual training tasks that are assigned to an employee.</description>
    <label>Training Task Assignment</label>
    <nameField>
        <displayFormat>TTA-{0000}</displayFormat>
        <label>Training Task Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Training Task Assignments</relationshipLabel>
    <relationshipName>Training_Task_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Duration_Mins__c.field-meta.xml
<CustomField>
    <fullName>Duration_Mins__c</fullName>
    <description>Expected number of minutes required. to complete the task.</description>
    <formula>Training_Task__r.Duration_Mins__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Expected number of minutes required. to complete the task.</inlineHelpText>
    <label>Duration Mins.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Program_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Program_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Assignment</label>
    <referenceTo>Program_Assignment__c</referenceTo>
    <relationshipLabel>Training Task Assignments</relationshipLabel>
    <relationshipName>Training_Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TrainingTaskAssignmentHandler.cls
public class TrainingTaskAssignmentHandler {
    public static void InsertProgramCompletedMinsAndTasks(List<Training_Task_Assignment__c> ttas){
        List<Program_Assignment__c> paSend = new List<Program_Assignment__c>();
        
        
        for(Training_Task_Assignment__c tta: ttas){     
            System.debug('tta.status = '+ tta.Status__c);
            if (tta.Program_Assignment__c != null){ //check if it's a stretch tta, (whether the task is related to a program assignment)
                System.debug('Working with: tta.name = ' + tta.Name + ' Program_Assignment__c = ' + tta.Program_Assignment__c);
                //case: status changes to complete, but loe minutes has not been rewarded to the program yet
                if (tta.Status__c == 'Complete'){//case: status changes to complete, but loe minutes has not been rewarded to the program yet
                    List<Program_Assignment__c> pas = [SELECT id,name,Completed_Mins__c,Number_of_Completed_Tasks__c
                                                       FROM Program_Assignment__c
                                                       WHERE id=:tta.Program_Assignment__c];
                    System.debug('List of PAs = '+pas);
                    for(Program_Assignment__c pa:pas){
                        System.debug('This TA\'s status is: ' + tta.Status__c);
                        if(pa.Completed_Mins__c != null){
                            pa.Completed_Mins__c += tta.Duration_Mins__c;
                            pa.Number_of_Completed_Tasks__c += 1;
                            paSend.add(pa);
                            System.debug('Added PA updates to DML');
                        }
                    }
                }
            }      
        }
        if (paSend.size() > 0){
            update paSend;
            System.debug('Sent DML');
        }
    }
    
    // update fields on program assignment related to the TTA
    public static void UpdateProgramCompletedMinsAndTasks(List<Training_Task_Assignment__c> ttas){
        List<Program_Assignment__c> paSend = new List<Program_Assignment__c>();
        for(Training_Task_Assignment__c tta: ttas){ 
            Training_Task_Assignment__c oldtta = (Training_Task_Assignment__c)Trigger.oldMap.get(tta.Id);            
            if (tta.Program_Assignment__c != null){ //check if it's a stretch tta, (whether the task is related to a program assignment)
                //case: status changes to complete, but loe minutes has not been rewarded to the program yet
                if (oldtta.Status__c != 'Complete' && tta.Status__c == 'Complete'){//case: status changes to complete, but loe minutes has not been rewarded to the program yet
                    List<Program_Assignment__c> pas = [SELECT id,name,Completed_Mins__c,Contact__c,Number_of_Completed_Tasks__c 
                                                FROM Program_Assignment__c 
                                                WHERE Contact__c = :tta.Contact__c];
                    for(Program_Assignment__c pa: pas){
                        if (pa.Completed_Mins__c == null) pa.Completed_Mins__c = 0; //if completed mins is null, then set to 0 so we can perform addition later
                        pa.Completed_Mins__c += tta.Duration_Mins__c; //update pa total completed mins
                        pa.Number_of_Completed_Tasks__c += 1; //increment pa total completed tasks
                        paSend.add(pa);
                    }
                }
                //case: status was originally complete and loe minutes were rewarded, but was changed to NOT complete
                else if(oldtta.Status__c == 'Complete' && tta.Status__c != 'Complete'){
                    List<Program_Assignment__c> pas = [SELECT id,name,Completed_Mins__c,Contact__c,Number_of_Completed_Tasks__c 
                                                FROM Program_Assignment__c 
                                                WHERE Contact__c = :tta.Contact__c];
                    for(Program_Assignment__c pa: pas){
                        if (pa.Completed_Mins__c == null) pa.Completed_Mins__c = 0; //if completed mins is null, then set to 0 so we can perform addition later
                        pa.Completed_Mins__c -= tta.Duration_Mins__c; 
                        pa.Number_of_Completed_Tasks__c -= 1; //decrement pa total completed tasks
                        paSend.add(pa);
                    }                    

                }
            }      
        }
        if (paSend.size() > 0){
            update paSend;
        }
    }
    
    public static void DeleteProgramCompletedMinsAndTasks(List<Training_Task_Assignment__c> ttas){
        List<Program_Assignment__c> paSend = new List<Program_Assignment__c>();
        for(Training_Task_Assignment__c tta: ttas){ 
            if (tta.Program_Assignment__c != null){ //check if it's a stretch tta, (whether the task is related to a program assignment)
                //case: if the old status was complete, deduct minutes from the pa LOE total
                if(tta.Status__c == 'Complete'){
                    List<Program_Assignment__c> pas = [SELECT id,name,Completed_Mins__c,Contact__c,Number_of_Completed_Tasks__c 
                                                FROM Program_Assignment__c 
                                                WHERE Contact__c = :tta.Contact__c];
                    for(Program_Assignment__c pa: pas){
                        if (pa.Completed_Mins__c == null) pa.Completed_Mins__c = 0; //if completed mins is null, then set to 0 so we can perform addition later
                        pa.Completed_Mins__c -= tta.Duration_Mins__c; 
                        pa.Number_of_Completed_Tasks__c -= 1;
                        paSend.add(pa);
                    }

                }
            }
        }
        if (paSend.size() > 0){
            update paSend;
        }
    }
    
    
}