force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Group of program task objects to assign to a CSG Employee</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Program_Duration_Days__c.field-meta.xml
<CustomField>
    <fullName>Program_Duration_Days__c</fullName>
    <inlineHelpText>How many days will it take to complete this program?</inlineHelpText>
    <label>Program Duration in Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <description>Relationship between programs and employees that they are being assigned.</description>
    <label>Program Assignment</label>
    <nameField>
        <displayFormat>PAS-{0000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProgramHandler.cls
public class ProgramHandler {
    public static void UpdateProgramAssignmentDueDate(List<Program__c> ps){
        List<Program_Assignment__c> paSend = new List<Program_Assignment__c>();
        for(Program__c p: ps){
            Program__c oldp = (Program__c)Trigger.oldMap.get(p.Id);
            if(oldp.Program_Duration_Days__c == null && p.Program_Duration_Days__c >= 1){ //case: if program duration in days was null, but changed to a valid input
                List<Program_Assignment__c> pas = [SELECT id,Program__c,End_Date__c
                                                   FROM Program_Assignment__c
                                                   WHERE Program__c = :p.Id];
                for(Program_Assignment__c pa: pas){
                    pa.End_Date__c = pa.Start_Date__c.addDays((Integer)p.Program_Duration_Days__c);
                    paSend.add(pa);
                }
            }
        }
        if(paSend.size() > 0){
            update paSend;
        }
        
        
    }
}