force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Group of program task objects to assign to a CSG Employee</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <description>Relationship between programs and employees that they are being assigned.</description>
    <label>Program Assignment</label>
    <nameField>
        <displayFormat>PAS-{0000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Ahead_Behind__c.field-meta.xml
<CustomField>
    <fullName>Ahead_Behind__c</fullName>
    <description>hh:mm format for the number of minutes the employee is ahead/behind on training tasks associated with this program.</description>
    <formula>&quot;(&quot;&amp;
TEXT(FLOOR(ABS(Ahead_Behind_Mins__c )/ 60))
&amp;&apos;hr &apos;&amp; 
TEXT(MOD(ABS(Ahead_Behind_Mins__c ),60))
&amp;&apos;min&apos;&amp;
&quot;)&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ahead/Behind</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Ratio between minutes earned vs. total minutes determining how far ahead or behind a user is within their assigned program. Calculated by Completed Minutes / Total Minutes by a +-25% criteria</description>
    <formula>IF(AND(Duration_Mins__c != 0, Completed_Mins__c = Duration_Mins__c), &apos;Complete&apos;,
IF(OR(Expected_Mins_Due__c = 0,AND(Expected_Mins_Due__c = 0, Completed_Mins__c = Expected_Mins_Due__c)), &apos;On Track&apos;,
IF(Completed_Mins__c / Expected_Mins_Due__c &lt;= 0.75, &apos;Far Behind&apos;,
IF(Completed_Mins__c / Expected_Mins_Due__c &lt; 1, &apos;Behind&apos;,
IF(Completed_Mins__c / Expected_Mins_Due__c &gt; 1.25, &apos;Far Ahead&apos;,
IF(Completed_Mins__c / Expected_Mins_Due__c &gt; 1, &apos;Far Ahead&apos;, &apos;N/A&apos;))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculated by Completed Mins. / Expected Mins. by a +-25% criteria (if Expected Mins. != 0)</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training_Task__c/Training_Task__c.object-meta.xml
<CustomObject>
    <description>Serves as template data about individual training activities.</description>
    <label>Training Task</label>
    <nameField>
        <label>Training Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Task_Assignment__c/Training_Task_Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction Object. Individual training tasks that are assigned to an employee.</description>
    <label>Training Task Assignment</label>
    <nameField>
        <displayFormat>TTA-{0000}</displayFormat>
        <label>Training Task Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Actual_Mins__c.field-meta.xml
<CustomField>
    <fullName>Actual_Mins__c</fullName>
    <inlineHelpText>Actual minutes taken to complete the task.</inlineHelpText>
    <label>Actual Mins.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Training Task Assignments</relationshipLabel>
    <relationshipName>Training_Task_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Training Task Assignments</relationshipLabel>
    <relationshipName>Training_Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Program_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Program_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Assignment</label>
    <referenceTo>Program_Assignment__c</referenceTo>
    <relationshipLabel>Training Task Assignments</relationshipLabel>
    <relationshipName>Training_Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Training_Task__c.field-meta.xml
<CustomField>
    <fullName>Training_Task__c</fullName>
    <label>Training Task</label>
    <referenceTo>Training_Task__c</referenceTo>
    <relationshipLabel>Training Task Assignments</relationshipLabel>
    <relationshipName>Training_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TrainingTaskAssignmentController.cls
public with sharing class TrainingTaskAssignmentController {
    @AuraEnabled(cacheable=true)
    public static List<Training_Task_Assignment__c> getTTAs(String paID){
        try {
            return [SELECT id, Training_Task__r.Name , Status__c, Start_Date__c, Due_Date__c, Date_Completed__c, Actual_Mins__c
                    FROM Training_Task_Assignment__c
                    WHERE Program_Assignment__c =:paID
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Program_Assignment__c> getPAs(String contactId){
        System.debug('contactId = ' + contactId );
        try {
            return [SELECT id, Program__r.Name, Contact__c, Status__c, Start_Date__c, End_Date__c, Ahead_Behind__c
                    FROM Program_Assignment__c
                    WHERE Contact__c =:contactId
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    public class TTADraftValues {
        // these variables need to be named the same as the JS variables passed into JSON deserializer, otherwise they would store null values
        public Id Id;
        public String Status;
        public Date Date_Completed;
        public Decimal Actual_Mins;
    }

    // bug: clicking an edit and leaving it null
    @AuraEnabled
    public static string updateTTAs(Object data) {
        System.debug('data = ' + data);
        // create a list of ttas that will be updated through DML
        List<Training_Task_Assignment__c> ttaUpdate = new List<Training_Task_Assignment__c>();
        // create a list of TTADraftValues that contains the TimeTakenInMinutes and Id
        List<TTADraftValues> ttaData = (List<TTADraftValues>) JSON.deserialize(
            JSON.serialize(data),
            List<TTADraftValues>.class
        );
        System.debug('ttaData = ' + ttaData);
        // create a map to quickly access tta record ID and it's new values
        Map<Id,TTADraftValues> ttaNewMap = new Map<Id,TTADraftValues>();
        // create a set to ensure key uniqueness and pass into SOQL
        Set<Id> ttaSet = new Set<Id>();
        for (TTADraftValues ttaDraftValue: ttaData){
            ttaNewMap.put(ttaDraftValue.Id, ttaDraftValue);
            ttaSet.add(ttaDraftValue.Id);
        }
        // query necessary fields and objects
        Map<ID,Training_Task_Assignment__c> ttaOldMap = new Map<ID,Training_Task_Assignment__c>(
            [SELECT Id, Status__c, Date_Completed__c, Actual_Mins__c
                FROM Training_Task_Assignment__c
                WHERE Id IN :ttaSet]
        );
        // replace old values with new values
        for (Id ttaID: ttaSet){
            Training_Task_Assignment__c tta = ttaOldMap.get(ttaID);
            // replace the value 
            // 1. if the new value != null
            // 2. if both new and old value are null (to handle the case where you click edit, but leave it as null)
            if (ttaNewMap.get(ttaID)?.Status != null ||
                (ttaNewMap.get(ttaID)?.Status == null && tta.Status__c == null)) { 
                tta.Status__c = ttaNewMap.get(ttaID)?.Status;
            }
            if (ttaNewMap.get(ttaID)?.Date_Completed != null  || 
                (ttaNewMap.get(ttaID)?.Date_Completed == null && tta.Date_Completed__c == null)) {
                tta.Date_Completed__c = ttaNewMap.get(ttaID)?.Date_Completed;
            }
            if (ttaNewMap.get(ttaID)?.Actual_Mins != null || 
                (ttaNewMap.get(ttaID)?.Actual_Mins == null && tta.Actual_Mins__c == null)) {
                tta.Actual_Mins__c = ttaNewMap.get(ttaID)?.Actual_Mins;

            }            
            ttaUpdate.add(tta);
        }
        try {
            if (ttaUpdate.size() > 0) update ttaUpdate;
            return 'Success: training task assignments updated successfully';
        }
        catch (Exception e) {
            return 'The following exception has occurred: ' + e.getMessage();
        }
    }
}