force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Group of program task objects to assign to a CSG Employee</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Duration_Mins__c.field-meta.xml
<CustomField>
    <fullName>Duration_Mins__c</fullName>
    <inlineHelpText>Total minutes required to complete all tasks within this program.</inlineHelpText>
    <label>Duration Mins.</label>
    <summarizedField>Program_Task__c.Duration_Mins__c</summarizedField>
    <summaryForeignKey>Program_Task__c.Program__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <description>Relationship between programs and employees that they are being assigned.</description>
    <label>Program Assignment</label>
    <nameField>
        <displayFormat>PAS-{0000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Duration_Mins__c.field-meta.xml
<CustomField>
    <fullName>Duration_Mins__c</fullName>
    <formula>Program__r.Duration_Mins__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration Mins.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Expected_Mins_Due__c.field-meta.xml
<CustomField>
    <fullName>Expected_Mins_Due__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This is the number of minutes an employee is expected to have so far. This number increases by the training task&apos;s &apos;duration mins.&apos; field when a training task is past due date. Used to calculate if an employee is ahead or behind schedule.</description>
    <inlineHelpText>The number of minutes an employee is expected to have at this time. This number is calculated/increases based on the training tasks&apos; due date.</inlineHelpText>
    <label>Expected Mins. Due</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/Training_Task_Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction Object. Individual training tasks that are assigned to an employee.</description>
    <label>Training Task Assignment</label>
    <nameField>
        <displayFormat>TTA-{0000}</displayFormat>
        <label>Training Task Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Training Task Assignments</relationshipLabel>
    <relationshipName>Training_Task_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Duration_Mins__c.field-meta.xml
<CustomField>
    <fullName>Duration_Mins__c</fullName>
    <description>Expected number of minutes required. to complete the task.</description>
    <formula>Training_Task__r.Duration_Mins__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Expected number of minutes required. to complete the task.</inlineHelpText>
    <label>Duration Mins.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Training Task Assignments</relationshipLabel>
    <relationshipName>Training_Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Program_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Program_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Assignment</label>
    <referenceTo>Program_Assignment__c</referenceTo>
    <relationshipLabel>Training Task Assignments</relationshipLabel>
    <relationshipName>Training_Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/scheduledProgramAssignmentLOE.cls
global class scheduledProgramAssignmentLOE implements Schedulable {
    global void execute(SchedulableContext sc) {
        calculateProgramAssignmentLOE();
    }
    public static void calculateProgramAssignmentLOE(){
        List<Program_Assignment__c> pasSend = new List<Program_Assignment__c>();
        List<Program_Assignment__c> pas = [SELECT id,Program__c,Contact__c
                                           FROM Program_Assignment__c];
  
        for(Program_Assignment__c pa: pas){
            List<Training_Task_Assignment__c> ttas = [SELECT id,Program_Assignment__c,Duration_Mins__c,Due_Date__c
                                                   FROM Training_Task_Assignment__c
                                                   WHERE Program_Assignment__c = :pa.id];
            //System.debug('For PA = '+ pa.Id + ' it has these TTAs = '+ttas);
            pa.Expected_Mins_Due__c = 0; //reset the value for each time the scheduled apex runs
            for(Training_Task_Assignment__c tta: ttas){ //perform sum
                if (tta.Program_Assignment__c != null && tta.Due_Date__c < date.today()){
                    pa.Expected_Mins_Due__c += tta.Duration_Mins__c;
                    //System.debug('Incremented expected mins for pa = '+pa.Id);
                }
            }
            pasSend.add(pa);
        }
        
        if(pasSend.size() > 0){
            //System.debug('Sending these PA for pasSend = '+pasSend);
            update pasSend;
        }
    }
}