force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Group of program task objects to assign to a CSG Employee</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Program_Duration_Days__c.field-meta.xml
<CustomField>
    <fullName>Program_Duration_Days__c</fullName>
    <inlineHelpText>How many days will it take to complete this program?</inlineHelpText>
    <label>Program Duration in Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <description>Relationship between programs and employees that they are being assigned.</description>
    <label>Program Assignment</label>
    <nameField>
        <displayFormat>PAS-{0000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <description>The date that this program was marked complete.</description>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Number_of_Assigned_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Assigned_Tasks__c</fullName>
    <formula>Program__r.Number_of_Tasks__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Assigned Tasks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Number_of_Completed_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Completed_Tasks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Completed Tasks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Ratio between minutes earned vs. total minutes determining how far ahead or behind a user is within their assigned program. Calculated by Completed Minutes / Total Minutes by a +-25% criteria</description>
    <formula>IF(AND(Duration_Mins__c != 0, Completed_Mins__c = Duration_Mins__c), &apos;Complete&apos;,
IF(OR(Expected_Mins_Due__c = 0,AND(Expected_Mins_Due__c = 0, Completed_Mins__c = Expected_Mins_Due__c)), &apos;On Track&apos;,
IF(Completed_Mins__c / Expected_Mins_Due__c &lt;= 0.75, &apos;Far Behind&apos;,
IF(Completed_Mins__c / Expected_Mins_Due__c &lt; 1, &apos;Behind&apos;,
IF(Completed_Mins__c / Expected_Mins_Due__c &gt; 1.25, &apos;Far Ahead&apos;,
IF(Completed_Mins__c / Expected_Mins_Due__c &gt; 1, &apos;Far Ahead&apos;, &apos;N/A&apos;))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculated by Completed Mins. / Expected Mins. by a +-25% criteria (if Expected Mins. != 0)</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Task__c/Program_Task__c.object-meta.xml
<CustomObject>
    <description>Relationship between programs and tasks objects.</description>
    <label>Program Task</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Program Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Task__c/fields/Due_Day__c.field-meta.xml
<CustomField>
    <fullName>Due_Day__c</fullName>
    <inlineHelpText>What day in this program is the task due?</inlineHelpText>
    <label>Due Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Task__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Tasks</relationshipLabel>
    <relationshipName>Program_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Task__c/fields/Training_Task__c.field-meta.xml
<CustomField>
    <fullName>Training_Task__c</fullName>
    <label>Training Task</label>
    <referenceTo>Training_Task__c</referenceTo>
    <relationshipLabel>Program Tasks</relationshipLabel>
    <relationshipName>Program_Tasks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Task__c/Training_Task__c.object-meta.xml
<CustomObject>
    <description>Serves as template data about individual training activities.</description>
    <label>Training Task</label>
    <nameField>
        <label>Training Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Task_Assignment__c/Training_Task_Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction Object. Individual training tasks that are assigned to an employee.</description>
    <label>Training Task Assignment</label>
    <nameField>
        <displayFormat>TTA-{0000}</displayFormat>
        <label>Training Task Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Training Task Assignments</relationshipLabel>
    <relationshipName>Training_Task_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Training Task Assignments</relationshipLabel>
    <relationshipName>Training_Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Program_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Program_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Assignment</label>
    <referenceTo>Program_Assignment__c</referenceTo>
    <relationshipLabel>Training Task Assignments</relationshipLabel>
    <relationshipName>Training_Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training_Task_Assignment__c/fields/Training_Task__c.field-meta.xml
<CustomField>
    <fullName>Training_Task__c</fullName>
    <label>Training Task</label>
    <referenceTo>Training_Task__c</referenceTo>
    <relationshipLabel>Training Task Assignments</relationshipLabel>
    <relationshipName>Training_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProgramAssignmentHandler.cls
public class ProgramAssignmentHandler {
    // Create the due date for the 'program assignment' based off the 'program' duration.
    public static void CreateDueDate(List<Program_Assignment__c> pas){
        for(Program_Assignment__c pa: pas){
            if(pa.Start_Date__c != null){
                Program__c p = [SELECT id,Name,Program_Duration_Days__c
                                FROM Program__c
                                WHERE id= :pa.Program__c];
                pa.End_Date__c = pa.Start_Date__c.addDays((Integer)p.Program_Duration_Days__c);
            }
        }
    }
    
    // Create 'training task assignment' records that belong to the 'program' in 'program assignment'
    public static void CreateRelatedTrainingTasks(List<Program_Assignment__c> pas){
        List<Training_Task_Assignment__c> ttaSend = new List<Training_Task_Assignment__c>(); //dml list of 'tta' records to create
        Map<id,String> ttaMap = new Map<id,String>(); //create a map of all the employee's tta's TA
        
        //query for program task association, then assign tasks based off that
        for(Program_Assignment__c pa: pas){
            //find associated training tasks
            List<Program_Task__c> pts = [SELECT id,Program__c,Training_Task__c,Due_Day__c 
                                         FROM Program_Task__c 
                                         WHERE Program__c= :pa.Program__c];
            
            //populate the ttaMap of all the employee's tta's TA
            for(Training_Task_Assignment__c tta:[SELECT id,Training_Task__c,Contact__c,Status__c
                                                 FROM Training_Task_Assignment__c
                                                 WHERE Contact__c = :pa.Contact__c]){
                                                     ttaMap.put(tta.Training_Task__c, tta.Status__c);
                                                 }         
            //I want the duplicate training task assignments to have the same status as one that currently exists (this only sets it to 'Not Started' w/ incorrect PA)
            for(Program_Task__c pt: pts){ //create training task assignments
                //if the employee already has thae TA in the ttaMAP, then then copy that TA's status
                Training_Task_Assignment__c tta;
                if(ttaMap.containsKey(pt.Training_Task__c)){
                    tta = new Training_Task_Assignment__c(Contact__c=pa.Contact__c,
                                                          Start_Date__c=pa.Start_Date__c,
                                                          Due_Date__c=pa.Start_Date__c.addDays((Integer)pt.Due_Day__c-1), //accurate due date requires -1 offset, use validation rule for {due day >= 1}
                                                          Program_Assignment__c=pa.Id,
                                                          Status__c=ttaMap.get(pt.Training_Task__c),
                                                          Training_Task__c=pt.Training_Task__c); 
                }else{
                    tta = new Training_Task_Assignment__c(Contact__c=pa.Contact__c,
                                                          Start_Date__c=pa.Start_Date__c,
                                                          Due_Date__c=pa.Start_Date__c.addDays((Integer)pt.Due_Day__c-1), //accurate due date requires -1 offset, use validation rule for {due day >= 1}
                                                          Program_Assignment__c=pa.Id,
                                                          Status__c='Not Started',
                                                          Training_Task__c=pt.Training_Task__c);
                }
                
                ttaSend.add(tta);
                }
         }
        if (ttaSend.size() > 0){
            insert ttaSend;
        }
    }
    
    public static void UpdateStatus(List<Program_Assignment__c> pas){
        for(Program_Assignment__c pa: pas){
          	Program_Assignment__c oldpa = (Program_Assignment__c)Trigger.oldMap.get(pa.Id);
            if(pa.Number_of_Completed_Tasks__c == pa.Number_of_Assigned_Tasks__c && oldpa.Completion_Date__c == null){
                pa.Completion_Date__c=date.today();
            } else if(pa.Number_of_Completed_Tasks__c < pa.Number_of_Assigned_Tasks__c && oldpa.Completion_Date__c != null){
                pa.Completion_Date__c=null;
            }
        }
    }
}