force-app/main/default/objects/Program_Task__c/Program_Task__c.object-meta.xml
<CustomObject>
    <description>Relationship between programs and tasks objects.</description>
    <label>Program Task</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Program Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Task__c/fields/Duration_Mins__c.field-meta.xml
<CustomField>
    <fullName>Duration_Mins__c</fullName>
    <label>Duration Mins.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Task__c/fields/Training_Task__c.field-meta.xml
<CustomField>
    <fullName>Training_Task__c</fullName>
    <label>Training Task</label>
    <referenceTo>Training_Task__c</referenceTo>
    <relationshipLabel>Program Tasks</relationshipLabel>
    <relationshipName>Program_Tasks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Task__c/Training_Task__c.object-meta.xml
<CustomObject>
    <description>Serves as template data about individual training activities.</description>
    <label>Training Task</label>
    <nameField>
        <label>Training Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Task__c/fields/Duration_Mins__c.field-meta.xml
<CustomField>
    <fullName>Duration_Mins__c</fullName>
    <description>Expected time to complete training task.</description>
    <inlineHelpText>Expected time to complete training task.</inlineHelpText>
    <label>Duration Mins.</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProgramTaskDurationMinsHandler.cls
public class ProgramTaskDurationMinsHandler {
    public static void UpsertDurationMins(List<Program_Task__c> pTasks){
        //List<Program_Task__c> pTaskSend = new List<Program_Task__c>(); //List to submit DML
        //List<Program_Task__c> pTasks = new List<Program_Task__c>(pTasksInput); //we need to instantiate the list object
        
        //query the training task associated with this program > set a value in the program field > add to DML List
        for(Program_Task__c pTask: pTasks){ 
        	Training_Task__c tTask = [SELECT id,Name,Duration_Mins__c FROM Training_Task__c WHERE id= :pTask.Training_Task__c];
            pTask.Duration_Mins__c = tTask.Duration_Mins__c;
            //pTaskSend.add(pTask);
        }
    }
}