force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Executive</fullName>
            </value>
            <value>
                <fullName>Customer Support</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Solution Consultant</fullName>
            </value>
            <value>
                <fullName>Technical Consultant</fullName>
            </value>
            <value>
                <fullName>Training Specialist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Employee.recordType-meta.xml
<RecordType>
    <fullName>Employee</fullName>
    <active>true</active>
    <label>Employee</label>
    
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Group of program task objects to assign to a CSG Employee</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Program_Duration_Days__c.field-meta.xml
<CustomField>
    <fullName>Program_Duration_Days__c</fullName>
    <inlineHelpText>How many days will it take to complete this program?</inlineHelpText>
    <label>Program Duration in Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <description>Relationship between programs and employees that they are being assigned.</description>
    <label>Program Assignment</label>
    <nameField>
        <displayFormat>PAS-{0000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignments</relationshipLabel>
    <relationshipName>Program_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProgramAssignmentToMultiUsersTests.cls
@isTest
private class ProgramAssignmentToMultiUsersTests {
    @TestSetup
    static void makeTestObjects(){

        RecordType rt = [SELECT id FROM RecordType WHERE Name =: 'Employee'];

        Contact testContact = new Contact();
        testContact.LastName = 'Smith';
        testContact.Role__c = 'Director';
        testContact.RecordTypeId = rt.id;
        insert testContact;

        Contact testContact2 = new Contact();
        testContact2.LastName = 'Jones';
        testContact2.Role__c = 'Technical Consultant';
        testContact2.ReportsToId = testContact.id;
        //Contact record type for Employee
        testContact2.RecordTypeId = rt.id;
        insert testContact2;

        Program__c testProgram = new Program__c();
        testProgram.Name = 'Intro to Development';
        testProgram.Program_Duration_Days__c= 12;
        insert testProgram;

        List<Program_Assignment__c> listOfProgramAssignments = new List<Program_Assignment__c>();
        Program_Assignment__c testProgramAssignment = new Program_Assignment__c();
        testProgramAssignment.Start_Date__c = date.Today();
        testProgramAssignment.Program__c = testProgram.id;
        testProgramAssignment.Contact__c = testContact.id;
        listOfProgramAssignments.add(testProgramAssignment);

        if (!listOfProgramAssignments.isEmpty()){
            insert testProgramAssignment;
        }
    }

    @isTest 
    static void getAvailableEmployeeTest() {
        Program__c myProgram= [SELECT id, Name FROM Program__c WHERE Name = 'Intro to Development'];
        List<Contact> actualResult = ProgramAssignmentToMultiUsersController.getAvailableEmployee(myProgram.id, '', '', '');

        Contact contact = [SELECT id, Name FROM Contact WHERE Role__c =: 'Director' AND LastName =: 'Smith'];
        Contact contact2 = [SELECT id, Name FROM Contact WHERE Role__c =: 'Technical Consultant' AND LastName =: 'Jones'];
        RecordType rc = [SELECT id FROM RecordType WHERE Name =: 'Employee'];

        List<Contact> expectedResult = new List<Contact>();
        Contact expectedContact = new Contact();
        expectedContact.Role__c = 'Director';
        expectedContact.LastName = 'Smith';
        expectedContact.Id = contact.Id;

        Contact expectedContact2 = new Contact();
        expectedContact2.id = contact2.id;
        expectedContact2.LastName = 'Jones';
        expectedContact2.Role__c = 'Technical Consultant';
        expectedContact2.RecordTypeId = rc.id;

        expectedResult.add(expectedContact2);

        System.assertEquals(expectedResult.size(), actualResult.size());
        System.assertEquals(expectedResult[0].id, actualResult[0].id);
        System.assertEquals(expectedResult[0].Role__c, actualResult[0].Role__c);
        System.assertEquals(expectedResult[0].LastName, actualResult[0].Name);
    }  

    @isTest 
    static void getFilteredEmployeesByManagerTest() {
        List<Contact> actualResult = ProgramAssignmentToMultiUsersController.getFilteredEmployees('', '', 'Smith');
        System.assertEquals('Smith', actualResult[0].ReportsToName__c);
        System.assertEquals('Technical Consultant', actualResult[0].Role__c);
        System.assertEquals(1, actualResult.size());
    }  
}